version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "client/"
    schedule:
      interval: "weekly"

  # Enable version updates for Cargo
  - package-ecosystem: "cargo"
    directory: "api/"
    schedule:
      interval: "weekly"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
